### ISSUE TITLE
Enhancement Request: Playback speed to 2.0

### ISSUE THREAD

**Issue by crogers2287** [izderadicka/audioserve-android#3]
Any chance you could increase the playback speed to increment all the way up to 2.0? I can't get it any faster than 1.25

**Comment by izderadicka** [comment]
Actually that was my "conscious"  decision - to have rather small range of speed adjustments with smaller steps. As I intended app primarily for audiobooks I though that small change in speed is useful however listen to audiobook in 2x faster speed does not make much sense, because it sounds awful.  
But that  only my opinion, if people think it make sense, it rather trivial to change it.

**Comment by crogers2287** [comment]
Ah understandable. I generally listen to all of my audiobooks at 1.7x.

**Comment by izderadicka** [comment]
b104d88 -  will make it into next version.  The customer is always right :-)

**Comment by izderadicka** [comment]
Released in v0.7.7
